[Service]
ExecStart=
ExecStart=/usr/bin/stdbuf -oL -eL /usr/local/lib/gts9-test390/hexagonrpcd -f /dev/fastrpc-adsp -d adsp -R /usr/share/qcom/sm8550/Samsung/gts9wifi
RuntimeMaxSec=120s
Restart=no
LogRateLimitIntervalSec=0
Environment=HEXAGONRPC_RETURN_TRACE=1
