# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_KEYBOARD_SAMSUNG_POGO_VENDOR_PORT) += samsung-pogo-v3.o
samsung-pogo-v3-y := stm32_pogo_i2c_v3.o stm32_pogo_core_v3.o \
		     stm32_pogo_cmd_v3.o stm32_pogo_fw.o \
		     stm32_pogo_interrupt_v3.o stm32_pogo_fn_v3.o
